- name: Add nvim repository to apt 
  ansible.builtin.apt_repository:
    repo: deb  https://ppa.launchpadcontent.net/neovim-ppa/unstable/ubuntu jammy main
    state: present
  become: true

- name: Add golang repository to apt
  ansible.builtin.apt_repository:
    repo: deb https://ppa.launchpadcontent.net/longsleep/golang-backports/ubuntu jammy main
    state: present
  become: true

- name: Install prereq tooling 
  ansible.builtin.apt:
    pkg:
    - git
    - pass # cred store for git
    - stow
    - curl
    - neovim
    - tmux
    - zsh
    - fonts-powerline # needed for some zsh plugins / themes font
    - fzf
    - ripgrep
    - golang-1.20
  become: true

- name: Install Snap Tools (Obsidian) 
  community.general.snap:
    name:
      - obsidian 
  become: true

- name: Change user shell to zsh 
  ansible.builtin.shell:
    cmd: chsh -s $(which zsh) {{ ansible_user_id }}
  become: true

- name: Install oh-my-zsh
  ansible.builtin.shell:
    cmd: sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh"

- name: Install nerd fonts
  ansible.builtin.shell:
    cmd: mkdir -p ~/.local/share/fonts && cd ~/.local/share/fonts && curl -fLO https://github.com/ryanoasis/nerd-fonts/raw/HEAD/patched-fonts/DroidSansMono/DroidSansMNerdFont-Regular.otf

- name: Install powerlevel10k theme
  ansible.builtin.shell:
    cmd: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
  args:
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/powerlevel10k"

- name: Install rip
  ansible.builtin.shell:
    cmd: wget https://github.com/nivekuil/rip/releases/download/0.12.0/rip && chmod +x rip && mv rip /usr/local/bin
  args:
    creates: "/usr/local/bin/rip"
  become: true

- name: Configure dotfiles
  ansible.builtin.shell:
    cmd: './install'
    chdir: '{{ playbook_dir}}/dotfiles'
  environment:
    DOTFILES: '{{ playbook_dir }}/dotfiles'
